// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/igm/v1/issue.proto

package igmb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// +++++create issue++++++++
type CreateIssueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory     string                 `protobuf:"bytes,4,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	IssueType       string                 `protobuf:"bytes,5,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LongDescription string                 `protobuf:"bytes,7,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	AdditionalDesc  *AdditionalDescription `protobuf:"bytes,9,opt,name=additional_desc,json=additionalDesc,proto3" json:"additional_desc,omitempty"`
	Items           []*IssueItem           `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateIssueRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateIssueRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *CreateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *CreateIssueRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreateIssueRequest) GetAdditionalDesc() *AdditionalDescription {
	if x != nil {
		return x.AdditionalDesc
	}
	return nil
}

func (x *CreateIssueRequest) GetItems() []*IssueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdditionalDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalDescription) Reset() {
	*x = AdditionalDescription{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalDescription) ProtoMessage() {}

func (x *AdditionalDescription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalDescription.ProtoReflect.Descriptor instead.
func (*AdditionalDescription) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{1}
}

func (x *AdditionalDescription) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdditionalDescription) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type IssueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueItem) Reset() {
	*x = IssueItem{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueItem) ProtoMessage() {}

func (x *IssueItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueItem.ProtoReflect.Descriptor instead.
func (*IssueItem) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{2}
}

func (x *IssueItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,6,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,7,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CreateIssueResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateIssueResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateIssueResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *CreateIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++update issue++++++++
type UpdateIssueRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	UserId                     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId                    string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId                    string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IssueType                  string                 `protobuf:"bytes,4,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Status                     string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ComplainantActionShortDesc string                 `protobuf:"bytes,6,opt,name=complainant_action_short_desc,json=complainantActionShortDesc,proto3" json:"complainant_action_short_desc,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *UpdateIssueRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateIssueRequest) GetComplainantActionShortDesc() string {
	if x != nil {
		return x.ComplainantActionShortDesc
	}
	return ""
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,4,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,5,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateIssueResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *UpdateIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++++close issue ++++++++++
type CloseIssueRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId               string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId               string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating                string                 `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` //closed
	ComplaintActShortDesc string                 `protobuf:"bytes,6,opt,name=complaint_act_short_desc,json=complaintActShortDesc,proto3" json:"complaint_act_short_desc,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CloseIssueRequest) Reset() {
	*x = CloseIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueRequest) ProtoMessage() {}

func (x *CloseIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueRequest.ProtoReflect.Descriptor instead.
func (*CloseIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{6}
}

func (x *CloseIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CloseIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CloseIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CloseIssueRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *CloseIssueRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloseIssueRequest) GetComplaintActShortDesc() string {
	if x != nil {
		return x.ComplaintActShortDesc
	}
	return ""
}

type CloseIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,3,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,4,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,5,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseIssueResponse) Reset() {
	*x = CloseIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueResponse) ProtoMessage() {}

func (x *CloseIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueResponse.ProtoReflect.Descriptor instead.
func (*CloseIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{7}
}

func (x *CloseIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CloseIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloseIssueResponse) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *CloseIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *CloseIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++++ get issue ++++++++++
type GetIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{8}
}

func (x *GetIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{9}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

// ++++++ list issues ++++++
type ListIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueRequest) Reset() {
	*x = ListIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueRequest) ProtoMessage() {}

func (x *ListIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueRequest.ProtoReflect.Descriptor instead.
func (*ListIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{10}
}

func (x *ListIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListIssueRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssueRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListIssueByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueByOrderRequest) Reset() {
	*x = ListIssueByOrderRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueByOrderRequest) ProtoMessage() {}

func (x *ListIssueByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueByOrderRequest.ProtoReflect.Descriptor instead.
func (*ListIssueByOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{11}
}

func (x *ListIssueByOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListIssueByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueResponse) Reset() {
	*x = ListIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueResponse) ProtoMessage() {}

func (x *ListIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueResponse.ProtoReflect.Descriptor instead.
func (*ListIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{12}
}

func (x *ListIssueResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListIssueResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListIssueResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssueResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	BapId         string                 `protobuf:"bytes,3,opt,name=bap_id,json=bapId,proto3" json:"bap_id,omitempty"`
	BppId         string                 `protobuf:"bytes,4,opt,name=bpp_id,json=bppId,proto3" json:"bpp_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{13}
}

func (x *Context) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Context) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Context) GetBapId() string {
	if x != nil {
		return x.BapId
	}
	return ""
}

func (x *Context) GetBppId() string {
	if x != nil {
		return x.BppId
	}
	return ""
}

func (x *Context) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Context) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type Org struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{14}
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{15}
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{16}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Contact       *Contact               `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Person        *Person                `protobuf:"bytes,3,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedBy) Reset() {
	*x = UpdatedBy{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedBy) ProtoMessage() {}

func (x *UpdatedBy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedBy.ProtoReflect.Descriptor instead.
func (*UpdatedBy) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatedBy) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

func (x *UpdatedBy) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *UpdatedBy) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type RespondentAction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RespondentAction string                 `protobuf:"bytes,1,opt,name=respondent_action,json=respondentAction,proto3" json:"respondent_action,omitempty"`
	ShortDesc        string                 `protobuf:"bytes,2,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy        *UpdatedBy             `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CascadedLevel    int32                  `protobuf:"varint,5,opt,name=cascaded_level,json=cascadedLevel,proto3" json:"cascaded_level,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RespondentAction) Reset() {
	*x = RespondentAction{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondentAction) ProtoMessage() {}

func (x *RespondentAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondentAction.ProtoReflect.Descriptor instead.
func (*RespondentAction) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{18}
}

func (x *RespondentAction) GetRespondentAction() string {
	if x != nil {
		return x.RespondentAction
	}
	return ""
}

func (x *RespondentAction) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *RespondentAction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RespondentAction) GetUpdatedBy() *UpdatedBy {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

func (x *RespondentAction) GetCascadedLevel() int32 {
	if x != nil {
		return x.CascadedLevel
	}
	return 0
}

type ComplainantAction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ComplainantAction string                 `protobuf:"bytes,1,opt,name=complainant_action,json=complainantAction,proto3" json:"complainant_action,omitempty"`
	ShortDesc         string                 `protobuf:"bytes,2,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy         *UpdatedBy             `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ComplainantAction) Reset() {
	*x = ComplainantAction{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplainantAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplainantAction) ProtoMessage() {}

func (x *ComplainantAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplainantAction.ProtoReflect.Descriptor instead.
func (*ComplainantAction) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{19}
}

func (x *ComplainantAction) GetComplainantAction() string {
	if x != nil {
		return x.ComplainantAction
	}
	return ""
}

func (x *ComplainantAction) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *ComplainantAction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ComplainantAction) GetUpdatedBy() *UpdatedBy {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

type IssueActions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ComplainantActions []*ComplainantAction   `protobuf:"bytes,1,rep,name=complainant_actions,json=complainantActions,proto3" json:"complainant_actions,omitempty"`
	RespondentActions  []*RespondentAction    `protobuf:"bytes,2,rep,name=respondent_actions,json=respondentActions,proto3" json:"respondent_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IssueActions) Reset() {
	*x = IssueActions{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueActions) ProtoMessage() {}

func (x *IssueActions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueActions.ProtoReflect.Descriptor instead.
func (*IssueActions) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{20}
}

func (x *IssueActions) GetComplainantActions() []*ComplainantAction {
	if x != nil {
		return x.ComplainantActions
	}
	return nil
}

func (x *IssueActions) GetRespondentActions() []*RespondentAction {
	if x != nil {
		return x.RespondentActions
	}
	return nil
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           *Org                   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Person        *Person                `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	Contact       *Contact               `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{21}
}

func (x *Organization) GetOrg() *Org {
	if x != nil {
		return x.Org
	}
	return nil
}

func (x *Organization) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *Organization) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type ResolutionProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Organization  *Organization          `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolutionProviderInfo) Reset() {
	*x = ResolutionProviderInfo{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionProviderInfo) ProtoMessage() {}

func (x *ResolutionProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionProviderInfo.ProtoReflect.Descriptor instead.
func (*ResolutionProviderInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{22}
}

func (x *ResolutionProviderInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResolutionProviderInfo) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ResolutionProvider struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	RespondentInfo *ResolutionProviderInfo `protobuf:"bytes,1,opt,name=respondent_info,json=respondentInfo,proto3" json:"respondent_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolutionProvider) Reset() {
	*x = ResolutionProvider{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolutionProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolutionProvider) ProtoMessage() {}

func (x *ResolutionProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolutionProvider.ProtoReflect.Descriptor instead.
func (*ResolutionProvider) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{23}
}

func (x *ResolutionProvider) GetRespondentInfo() *ResolutionProviderInfo {
	if x != nil {
		return x.RespondentInfo
	}
	return nil
}

type Resolution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShortDesc       string                 `protobuf:"bytes,1,opt,name=short_desc,json=shortDesc,proto3" json:"short_desc,omitempty"`
	LongDesc        string                 `protobuf:"bytes,2,opt,name=long_desc,json=longDesc,proto3" json:"long_desc,omitempty"`
	ActionTriggered string                 `protobuf:"bytes,3,opt,name=action_triggered,json=actionTriggered,proto3" json:"action_triggered,omitempty"`
	RefundAmount    string                 `protobuf:"bytes,4,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{24}
}

func (x *Resolution) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *Resolution) GetLongDesc() string {
	if x != nil {
		return x.LongDesc
	}
	return ""
}

func (x *Resolution) GetActionTriggered() string {
	if x != nil {
		return x.ActionTriggered
	}
	return ""
}

func (x *Resolution) GetRefundAmount() string {
	if x != nil {
		return x.RefundAmount
	}
	return ""
}

type IncomingIssue struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	IssueType          string                 `protobuf:"bytes,3,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Category           string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory        string                 `protobuf:"bytes,5,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	IssueActions       *IssueActions          `protobuf:"bytes,6,opt,name=issue_actions,json=issueActions,proto3" json:"issue_actions,omitempty"`
	ResolutionProvider *ResolutionProvider    `protobuf:"bytes,7,opt,name=resolution_provider,json=resolutionProvider,proto3" json:"resolution_provider,omitempty"`
	Resolution         *Resolution            `protobuf:"bytes,8,opt,name=resolution,proto3" json:"resolution,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IncomingIssue) Reset() {
	*x = IncomingIssue{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingIssue) ProtoMessage() {}

func (x *IncomingIssue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingIssue.ProtoReflect.Descriptor instead.
func (*IncomingIssue) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{25}
}

func (x *IncomingIssue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncomingIssue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IncomingIssue) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *IncomingIssue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IncomingIssue) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *IncomingIssue) GetIssueActions() *IssueActions {
	if x != nil {
		return x.IssueActions
	}
	return nil
}

func (x *IncomingIssue) GetResolutionProvider() *ResolutionProvider {
	if x != nil {
		return x.ResolutionProvider
	}
	return nil
}

func (x *IncomingIssue) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *IncomingIssue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *IncomingIssue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OnIssuePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Issue         *IncomingIssue         `protobuf:"bytes,2,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssuePayload) Reset() {
	*x = OnIssuePayload{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssuePayload) ProtoMessage() {}

func (x *OnIssuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssuePayload.ProtoReflect.Descriptor instead.
func (*OnIssuePayload) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{26}
}

func (x *OnIssuePayload) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *OnIssuePayload) GetIssue() *IncomingIssue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type OnIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       *OnIssuePayload        `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueRequest) Reset() {
	*x = OnIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueRequest) ProtoMessage() {}

func (x *OnIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueRequest.ProtoReflect.Descriptor instead.
func (*OnIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{27}
}

func (x *OnIssueRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OnIssueRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OnIssueRequest) GetPayload() *OnIssuePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OnIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueResponse) Reset() {
	*x = OnIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueResponse) ProtoMessage() {}

func (x *OnIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueResponse.ProtoReflect.Descriptor instead.
func (*OnIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{28}
}

func (x *OnIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OnIssueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,3,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Payload       *OnIssuePayload        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueStatusRequest) Reset() {
	*x = OnIssueStatusRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueStatusRequest) ProtoMessage() {}

func (x *OnIssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueStatusRequest.ProtoReflect.Descriptor instead.
func (*OnIssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{29}
}

func (x *OnIssueStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OnIssueStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OnIssueStatusRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *OnIssueStatusRequest) GetPayload() *OnIssuePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OnIssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueStatusResponse) Reset() {
	*x = OnIssueStatusResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueStatusResponse) ProtoMessage() {}

func (x *OnIssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueStatusResponse.ProtoReflect.Descriptor instead.
func (*OnIssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{30}
}

func (x *OnIssueStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnIssueStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IssueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueStatusRequest) Reset() {
	*x = IssueStatusRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueStatusRequest) ProtoMessage() {}

func (x *IssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueStatusRequest.ProtoReflect.Descriptor instead.
func (*IssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{31}
}

func (x *IssueStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueStatusRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type IssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OndcSent      bool                   `protobuf:"varint,4,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,5,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueStatusResponse) Reset() {
	*x = IssueStatusResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueStatusResponse) ProtoMessage() {}

func (x *IssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueStatusResponse.ProtoReflect.Descriptor instead.
func (*IssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{32}
}

func (x *IssueStatusResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *IssueStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IssueStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IssueStatusResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *IssueStatusResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

type Issue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IssueId          string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId    string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Category         string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,6,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	IssueType        string                 `protobuf:"bytes,7,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	DescriptionShort string                 `protobuf:"bytes,9,opt,name=description_short,json=descriptionShort,proto3" json:"description_short,omitempty"`
	DescriptionLong  string                 `protobuf:"bytes,10,opt,name=description_long,json=descriptionLong,proto3" json:"description_long,omitempty"`
	ImageUrls        []string               `protobuf:"bytes,11,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	BppId            string                 `protobuf:"bytes,12,opt,name=bpp_id,json=bppId,proto3" json:"bpp_id,omitempty"`
	BppUri           string                 `protobuf:"bytes,13,opt,name=bpp_uri,json=bppUri,proto3" json:"bpp_uri,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{33}
}

func (x *Issue) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *Issue) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Issue) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Issue) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Issue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Issue) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *Issue) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *Issue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Issue) GetDescriptionShort() string {
	if x != nil {
		return x.DescriptionShort
	}
	return ""
}

func (x *Issue) GetDescriptionLong() string {
	if x != nil {
		return x.DescriptionLong
	}
	return ""
}

func (x *Issue) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Issue) GetBppId() string {
	if x != nil {
		return x.BppId
	}
	return ""
}

func (x *Issue) GetBppUri() string {
	if x != nil {
		return x.BppUri
	}
	return ""
}

func (x *Issue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Issue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_proto_igm_v1_issue_proto protoreflect.FileDescriptor

const file_api_proto_igm_v1_issue_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/igm/v1/issue.proto\x12\x06igm.v1\"\x83\x03\n" +
	"\x12CreateIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x04 \x01(\tR\vsubCategory\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x05 \x01(\tR\tissueType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\a \x01(\tR\x0flongDescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12F\n" +
	"\x0fadditional_desc\x18\t \x01(\v2\x1d.igm.v1.AdditionalDescriptionR\x0eadditionalDesc\x12'\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x11.igm.v1.IssueItemR\x05items\"L\n" +
	"\x15AdditionalDescription\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"7\n" +
	"\tIssueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xe9\x01\n" +
	"\x13CreateIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tondc_sent\x18\x06 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\a \x01(\tR\vondcMessage\"\xdd\x01\n" +
	"\x12UpdateIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x04 \x01(\tR\tissueType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12A\n" +
	"\x1dcomplainant_action_short_desc\x18\x06 \x01(\tR\x1acomplainantActionShortDesc\"\xa7\x01\n" +
	"\x13UpdateIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tondc_sent\x18\x04 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\x05 \x01(\tR\vondcMessage\"\xcb\x01\n" +
	"\x11CloseIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x127\n" +
	"\x18complaint_act_short_desc\x18\x06 \x01(\tR\x15complaintActShortDesc\"\xa4\x01\n" +
	"\x12CloseIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tclosed_at\x18\x03 \x01(\tR\bclosedAt\x12\x1b\n" +
	"\tondc_sent\x18\x04 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\x05 \x01(\tR\vondcMessage\"E\n" +
	"\x0fGetIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"7\n" +
	"\x10GetIssueResponse\x12#\n" +
	"\x05issue\x18\x01 \x01(\v2\r.igm.v1.IssueR\x05issue\"\\\n" +
	"\x10ListIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"M\n" +
	"\x17ListIssueByOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x8c\x01\n" +
	"\x11ListIssueResponse\x12%\n" +
	"\x06issues\x18\x01 \x03(\v2\r.igm.v1.IssueR\x06issues\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xad\x01\n" +
	"\aContext\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x15\n" +
	"\x06bap_id\x18\x03 \x01(\tR\x05bapId\x12\x15\n" +
	"\x06bpp_id\x18\x04 \x01(\tR\x05bppId\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\"\x19\n" +
	"\x03Org\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\aContact\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x1c\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"}\n" +
	"\tUpdatedBy\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.igm.v1.OrgR\x03org\x12)\n" +
	"\acontact\x18\x02 \x01(\v2\x0f.igm.v1.ContactR\acontact\x12&\n" +
	"\x06person\x18\x03 \x01(\v2\x0e.igm.v1.PersonR\x06person\"\xd6\x01\n" +
	"\x10RespondentAction\x12+\n" +
	"\x11respondent_action\x18\x01 \x01(\tR\x10respondentAction\x12\x1d\n" +
	"\n" +
	"short_desc\x18\x02 \x01(\tR\tshortDesc\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x120\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\v2\x11.igm.v1.UpdatedByR\tupdatedBy\x12%\n" +
	"\x0ecascaded_level\x18\x05 \x01(\x05R\rcascadedLevel\"\xb2\x01\n" +
	"\x11ComplainantAction\x12-\n" +
	"\x12complainant_action\x18\x01 \x01(\tR\x11complainantAction\x12\x1d\n" +
	"\n" +
	"short_desc\x18\x02 \x01(\tR\tshortDesc\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x120\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\v2\x11.igm.v1.UpdatedByR\tupdatedBy\"\xa3\x01\n" +
	"\fIssueActions\x12J\n" +
	"\x13complainant_actions\x18\x01 \x03(\v2\x19.igm.v1.ComplainantActionR\x12complainantActions\x12G\n" +
	"\x12respondent_actions\x18\x02 \x03(\v2\x18.igm.v1.RespondentActionR\x11respondentActions\"\x80\x01\n" +
	"\fOrganization\x12\x1d\n" +
	"\x03org\x18\x01 \x01(\v2\v.igm.v1.OrgR\x03org\x12&\n" +
	"\x06person\x18\x02 \x01(\v2\x0e.igm.v1.PersonR\x06person\x12)\n" +
	"\acontact\x18\x03 \x01(\v2\x0f.igm.v1.ContactR\acontact\"f\n" +
	"\x16ResolutionProviderInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\forganization\x18\x02 \x01(\v2\x14.igm.v1.OrganizationR\forganization\"]\n" +
	"\x12ResolutionProvider\x12G\n" +
	"\x0frespondent_info\x18\x01 \x01(\v2\x1e.igm.v1.ResolutionProviderInfoR\x0erespondentInfo\"\x98\x01\n" +
	"\n" +
	"Resolution\x12\x1d\n" +
	"\n" +
	"short_desc\x18\x01 \x01(\tR\tshortDesc\x12\x1b\n" +
	"\tlong_desc\x18\x02 \x01(\tR\blongDesc\x12)\n" +
	"\x10action_triggered\x18\x03 \x01(\tR\x0factionTriggered\x12#\n" +
	"\rrefund_amount\x18\x04 \x01(\tR\frefundAmount\"\x8f\x03\n" +
	"\rIncomingIssue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x03 \x01(\tR\tissueType\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x05 \x01(\tR\vsubCategory\x129\n" +
	"\rissue_actions\x18\x06 \x01(\v2\x14.igm.v1.IssueActionsR\fissueActions\x12K\n" +
	"\x13resolution_provider\x18\a \x01(\v2\x1a.igm.v1.ResolutionProviderR\x12resolutionProvider\x122\n" +
	"\n" +
	"resolution\x18\b \x01(\v2\x12.igm.v1.ResolutionR\n" +
	"resolution\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"h\n" +
	"\x0eOnIssuePayload\x12)\n" +
	"\acontext\x18\x01 \x01(\v2\x0f.igm.v1.ContextR\acontext\x12+\n" +
	"\x05issue\x18\x02 \x01(\v2\x15.igm.v1.IncomingIssueR\x05issue\"\x88\x01\n" +
	"\x0eOnIssueRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x120\n" +
	"\apayload\x18\n" +
	" \x01(\v2\x16.igm.v1.OnIssuePayloadR\apayload\"C\n" +
	"\x0fOnIssueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa9\x01\n" +
	"\x14OnIssueStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x19\n" +
	"\bissue_id\x18\x03 \x01(\tR\aissueId\x120\n" +
	"\apayload\x18\x04 \x01(\v2\x16.igm.v1.OnIssuePayloadR\apayload\"I\n" +
	"\x15OnIssueStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x12IssueStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"\xa2\x01\n" +
	"\x13IssueStatusResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\tondc_sent\x18\x04 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\x05 \x01(\tR\vondcMessage\"\xd8\x03\n" +
	"\x05Issue\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x06 \x01(\tR\vsubCategory\x12\x1d\n" +
	"\n" +
	"issue_type\x18\a \x01(\tR\tissueType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12+\n" +
	"\x11description_short\x18\t \x01(\tR\x10descriptionShort\x12)\n" +
	"\x10description_long\x18\n" +
	" \x01(\tR\x0fdescriptionLong\x12\x1d\n" +
	"\n" +
	"image_urls\x18\v \x03(\tR\timageUrls\x12\x15\n" +
	"\x06bpp_id\x18\f \x01(\tR\x05bppId\x12\x17\n" +
	"\abpp_uri\x18\r \x01(\tR\x06bppUri\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt2\x99\x05\n" +
	"\fIssueService\x12F\n" +
	"\vCreateIssue\x12\x1a.igm.v1.CreateIssueRequest\x1a\x1b.igm.v1.CreateIssueResponse\x12F\n" +
	"\vUpdateIssue\x12\x1a.igm.v1.UpdateIssueRequest\x1a\x1b.igm.v1.UpdateIssueResponse\x12C\n" +
	"\n" +
	"CloseIssue\x12\x19.igm.v1.CloseIssueRequest\x1a\x1a.igm.v1.CloseIssueResponse\x12=\n" +
	"\bGetIssue\x12\x17.igm.v1.GetIssueRequest\x1a\x18.igm.v1.GetIssueResponse\x12A\n" +
	"\n" +
	"ListIssues\x12\x18.igm.v1.ListIssueRequest\x1a\x19.igm.v1.ListIssueResponse\x12N\n" +
	"\x10ListIssueByOrder\x12\x1f.igm.v1.ListIssueByOrderRequest\x1a\x19.igm.v1.ListIssueResponse\x12L\n" +
	"\x11HandleIssueStatus\x12\x1a.igm.v1.IssueStatusRequest\x1a\x1b.igm.v1.IssueStatusResponse\x12@\n" +
	"\rHandleOnIssue\x12\x16.igm.v1.OnIssueRequest\x1a\x17.igm.v1.OnIssueResponse\x12R\n" +
	"\x13HandleOnIssueStatus\x12\x1c.igm.v1.OnIssueStatusRequest\x1a\x1d.igm.v1.OnIssueStatusResponseB/Z-github/effimove/igm-svc/api/proto/igm/v1;igmbb\x06proto3"

var (
	file_api_proto_igm_v1_issue_proto_rawDescOnce sync.Once
	file_api_proto_igm_v1_issue_proto_rawDescData []byte
)

func file_api_proto_igm_v1_issue_proto_rawDescGZIP() []byte {
	file_api_proto_igm_v1_issue_proto_rawDescOnce.Do(func() {
		file_api_proto_igm_v1_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_igm_v1_issue_proto_rawDesc), len(file_api_proto_igm_v1_issue_proto_rawDesc)))
	})
	return file_api_proto_igm_v1_issue_proto_rawDescData
}

var file_api_proto_igm_v1_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_igm_v1_issue_proto_goTypes = []any{
	(*CreateIssueRequest)(nil),      // 0: igm.v1.CreateIssueRequest
	(*AdditionalDescription)(nil),   // 1: igm.v1.AdditionalDescription
	(*IssueItem)(nil),               // 2: igm.v1.IssueItem
	(*CreateIssueResponse)(nil),     // 3: igm.v1.CreateIssueResponse
	(*UpdateIssueRequest)(nil),      // 4: igm.v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),     // 5: igm.v1.UpdateIssueResponse
	(*CloseIssueRequest)(nil),       // 6: igm.v1.CloseIssueRequest
	(*CloseIssueResponse)(nil),      // 7: igm.v1.CloseIssueResponse
	(*GetIssueRequest)(nil),         // 8: igm.v1.GetIssueRequest
	(*GetIssueResponse)(nil),        // 9: igm.v1.GetIssueResponse
	(*ListIssueRequest)(nil),        // 10: igm.v1.ListIssueRequest
	(*ListIssueByOrderRequest)(nil), // 11: igm.v1.ListIssueByOrderRequest
	(*ListIssueResponse)(nil),       // 12: igm.v1.ListIssueResponse
	(*Context)(nil),                 // 13: igm.v1.Context
	(*Org)(nil),                     // 14: igm.v1.Org
	(*Contact)(nil),                 // 15: igm.v1.Contact
	(*Person)(nil),                  // 16: igm.v1.Person
	(*UpdatedBy)(nil),               // 17: igm.v1.UpdatedBy
	(*RespondentAction)(nil),        // 18: igm.v1.RespondentAction
	(*ComplainantAction)(nil),       // 19: igm.v1.ComplainantAction
	(*IssueActions)(nil),            // 20: igm.v1.IssueActions
	(*Organization)(nil),            // 21: igm.v1.Organization
	(*ResolutionProviderInfo)(nil),  // 22: igm.v1.ResolutionProviderInfo
	(*ResolutionProvider)(nil),      // 23: igm.v1.ResolutionProvider
	(*Resolution)(nil),              // 24: igm.v1.Resolution
	(*IncomingIssue)(nil),           // 25: igm.v1.IncomingIssue
	(*OnIssuePayload)(nil),          // 26: igm.v1.OnIssuePayload
	(*OnIssueRequest)(nil),          // 27: igm.v1.OnIssueRequest
	(*OnIssueResponse)(nil),         // 28: igm.v1.OnIssueResponse
	(*OnIssueStatusRequest)(nil),    // 29: igm.v1.OnIssueStatusRequest
	(*OnIssueStatusResponse)(nil),   // 30: igm.v1.OnIssueStatusResponse
	(*IssueStatusRequest)(nil),      // 31: igm.v1.IssueStatusRequest
	(*IssueStatusResponse)(nil),     // 32: igm.v1.IssueStatusResponse
	(*Issue)(nil),                   // 33: igm.v1.Issue
}
var file_api_proto_igm_v1_issue_proto_depIdxs = []int32{
	1,  // 0: igm.v1.CreateIssueRequest.additional_desc:type_name -> igm.v1.AdditionalDescription
	2,  // 1: igm.v1.CreateIssueRequest.items:type_name -> igm.v1.IssueItem
	33, // 2: igm.v1.GetIssueResponse.issue:type_name -> igm.v1.Issue
	33, // 3: igm.v1.ListIssueResponse.issues:type_name -> igm.v1.Issue
	14, // 4: igm.v1.UpdatedBy.org:type_name -> igm.v1.Org
	15, // 5: igm.v1.UpdatedBy.contact:type_name -> igm.v1.Contact
	16, // 6: igm.v1.UpdatedBy.person:type_name -> igm.v1.Person
	17, // 7: igm.v1.RespondentAction.updated_by:type_name -> igm.v1.UpdatedBy
	17, // 8: igm.v1.ComplainantAction.updated_by:type_name -> igm.v1.UpdatedBy
	19, // 9: igm.v1.IssueActions.complainant_actions:type_name -> igm.v1.ComplainantAction
	18, // 10: igm.v1.IssueActions.respondent_actions:type_name -> igm.v1.RespondentAction
	14, // 11: igm.v1.Organization.org:type_name -> igm.v1.Org
	16, // 12: igm.v1.Organization.person:type_name -> igm.v1.Person
	15, // 13: igm.v1.Organization.contact:type_name -> igm.v1.Contact
	21, // 14: igm.v1.ResolutionProviderInfo.organization:type_name -> igm.v1.Organization
	22, // 15: igm.v1.ResolutionProvider.respondent_info:type_name -> igm.v1.ResolutionProviderInfo
	20, // 16: igm.v1.IncomingIssue.issue_actions:type_name -> igm.v1.IssueActions
	23, // 17: igm.v1.IncomingIssue.resolution_provider:type_name -> igm.v1.ResolutionProvider
	24, // 18: igm.v1.IncomingIssue.resolution:type_name -> igm.v1.Resolution
	13, // 19: igm.v1.OnIssuePayload.context:type_name -> igm.v1.Context
	25, // 20: igm.v1.OnIssuePayload.issue:type_name -> igm.v1.IncomingIssue
	26, // 21: igm.v1.OnIssueRequest.payload:type_name -> igm.v1.OnIssuePayload
	26, // 22: igm.v1.OnIssueStatusRequest.payload:type_name -> igm.v1.OnIssuePayload
	0,  // 23: igm.v1.IssueService.CreateIssue:input_type -> igm.v1.CreateIssueRequest
	4,  // 24: igm.v1.IssueService.UpdateIssue:input_type -> igm.v1.UpdateIssueRequest
	6,  // 25: igm.v1.IssueService.CloseIssue:input_type -> igm.v1.CloseIssueRequest
	8,  // 26: igm.v1.IssueService.GetIssue:input_type -> igm.v1.GetIssueRequest
	10, // 27: igm.v1.IssueService.ListIssues:input_type -> igm.v1.ListIssueRequest
	11, // 28: igm.v1.IssueService.ListIssueByOrder:input_type -> igm.v1.ListIssueByOrderRequest
	31, // 29: igm.v1.IssueService.HandleIssueStatus:input_type -> igm.v1.IssueStatusRequest
	27, // 30: igm.v1.IssueService.HandleOnIssue:input_type -> igm.v1.OnIssueRequest
	29, // 31: igm.v1.IssueService.HandleOnIssueStatus:input_type -> igm.v1.OnIssueStatusRequest
	3,  // 32: igm.v1.IssueService.CreateIssue:output_type -> igm.v1.CreateIssueResponse
	5,  // 33: igm.v1.IssueService.UpdateIssue:output_type -> igm.v1.UpdateIssueResponse
	7,  // 34: igm.v1.IssueService.CloseIssue:output_type -> igm.v1.CloseIssueResponse
	9,  // 35: igm.v1.IssueService.GetIssue:output_type -> igm.v1.GetIssueResponse
	12, // 36: igm.v1.IssueService.ListIssues:output_type -> igm.v1.ListIssueResponse
	12, // 37: igm.v1.IssueService.ListIssueByOrder:output_type -> igm.v1.ListIssueResponse
	32, // 38: igm.v1.IssueService.HandleIssueStatus:output_type -> igm.v1.IssueStatusResponse
	28, // 39: igm.v1.IssueService.HandleOnIssue:output_type -> igm.v1.OnIssueResponse
	30, // 40: igm.v1.IssueService.HandleOnIssueStatus:output_type -> igm.v1.OnIssueStatusResponse
	32, // [32:41] is the sub-list for method output_type
	23, // [23:32] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_proto_igm_v1_issue_proto_init() }
func file_api_proto_igm_v1_issue_proto_init() {
	if File_api_proto_igm_v1_issue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_igm_v1_issue_proto_rawDesc), len(file_api_proto_igm_v1_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_igm_v1_issue_proto_goTypes,
		DependencyIndexes: file_api_proto_igm_v1_issue_proto_depIdxs,
		MessageInfos:      file_api_proto_igm_v1_issue_proto_msgTypes,
	}.Build()
	File_api_proto_igm_v1_issue_proto = out.File
	file_api_proto_igm_v1_issue_proto_goTypes = nil
	file_api_proto_igm_v1_issue_proto_depIdxs = nil
}
