// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/igm/v1/issue.proto

package igmb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// +++++create issue++++++++
type CreateIssueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory     string                 `protobuf:"bytes,4,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	IssueType       string                 `protobuf:"bytes,5,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LongDescription string                 `protobuf:"bytes,7,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	AdditionalDesc  *AdditionalDescription `protobuf:"bytes,9,opt,name=additional_desc,json=additionalDesc,proto3" json:"additional_desc,omitempty"`
	Items           []*IssueItem           `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateIssueRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateIssueRequest) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *CreateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *CreateIssueRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreateIssueRequest) GetAdditionalDesc() *AdditionalDescription {
	if x != nil {
		return x.AdditionalDesc
	}
	return nil
}

func (x *CreateIssueRequest) GetItems() []*IssueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdditionalDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalDescription) Reset() {
	*x = AdditionalDescription{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalDescription) ProtoMessage() {}

func (x *AdditionalDescription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalDescription.ProtoReflect.Descriptor instead.
func (*AdditionalDescription) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{1}
}

func (x *AdditionalDescription) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdditionalDescription) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type IssueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueItem) Reset() {
	*x = IssueItem{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueItem) ProtoMessage() {}

func (x *IssueItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueItem.ProtoReflect.Descriptor instead.
func (*IssueItem) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{2}
}

func (x *IssueItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssueItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` //open
	TransactionId string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,6,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,7,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CreateIssueResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateIssueResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateIssueResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *CreateIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++update issue++++++++
type UpdateIssueRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	UserId                     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId                    string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId                    string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IssueType                  string                 `protobuf:"bytes,4,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Status                     string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` //new status
	ComplainantActionShortDesc string                 `protobuf:"bytes,6,opt,name=complainant_action_short_desc,json=complainantActionShortDesc,proto3" json:"complainant_action_short_desc,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateIssueRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *UpdateIssueRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateIssueRequest) GetComplainantActionShortDesc() string {
	if x != nil {
		return x.ComplainantActionShortDesc
	}
	return ""
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,4,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,5,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateIssueResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UpdateIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *UpdateIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++++close issue ++++++++++
type CloseIssueRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId               string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId               string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating                string                 `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` //closed
	ComplaintActShortDesc string                 `protobuf:"bytes,6,opt,name=complaint_act_short_desc,json=complaintActShortDesc,proto3" json:"complaint_act_short_desc,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CloseIssueRequest) Reset() {
	*x = CloseIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueRequest) ProtoMessage() {}

func (x *CloseIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueRequest.ProtoReflect.Descriptor instead.
func (*CloseIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{6}
}

func (x *CloseIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CloseIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CloseIssueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CloseIssueRequest) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *CloseIssueRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloseIssueRequest) GetComplaintActShortDesc() string {
	if x != nil {
		return x.ComplaintActShortDesc
	}
	return ""
}

type CloseIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,3,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	OndcSent      bool                   `protobuf:"varint,4,opt,name=ondc_sent,json=ondcSent,proto3" json:"ondc_sent,omitempty"`
	OndcMessage   string                 `protobuf:"bytes,5,opt,name=ondc_message,json=ondcMessage,proto3" json:"ondc_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseIssueResponse) Reset() {
	*x = CloseIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueResponse) ProtoMessage() {}

func (x *CloseIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueResponse.ProtoReflect.Descriptor instead.
func (*CloseIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{7}
}

func (x *CloseIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *CloseIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloseIssueResponse) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *CloseIssueResponse) GetOndcSent() bool {
	if x != nil {
		return x.OndcSent
	}
	return false
}

func (x *CloseIssueResponse) GetOndcMessage() string {
	if x != nil {
		return x.OndcMessage
	}
	return ""
}

// ++++++++ get issue ++++++++++
type GetIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{8}
}

func (x *GetIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{9}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

// ++++++ list issues ++++++
type ListIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueRequest) Reset() {
	*x = ListIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueRequest) ProtoMessage() {}

func (x *ListIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueRequest.ProtoReflect.Descriptor instead.
func (*ListIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{10}
}

func (x *ListIssueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListIssueRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssueRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListIssueByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueByOrderRequest) Reset() {
	*x = ListIssueByOrderRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueByOrderRequest) ProtoMessage() {}

func (x *ListIssueByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueByOrderRequest.ProtoReflect.Descriptor instead.
func (*ListIssueByOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{11}
}

func (x *ListIssueByOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListIssueByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSizee     int32                  `protobuf:"varint,4,opt,name=page_sizee,json=pageSizee,proto3" json:"page_sizee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueResponse) Reset() {
	*x = ListIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueResponse) ProtoMessage() {}

func (x *ListIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueResponse.ProtoReflect.Descriptor instead.
func (*ListIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{12}
}

func (x *ListIssueResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListIssueResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListIssueResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIssueResponse) GetPageSizee() int32 {
	if x != nil {
		return x.PageSizee
	}
	return 0
}

type OnIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueRequest) Reset() {
	*x = OnIssueRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueRequest) ProtoMessage() {}

func (x *OnIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueRequest.ProtoReflect.Descriptor instead.
func (*OnIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{13}
}

func (x *OnIssueRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OnIssueRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OnIssueRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type OnIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueResponse) Reset() {
	*x = OnIssueResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueResponse) ProtoMessage() {}

func (x *OnIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueResponse.ProtoReflect.Descriptor instead.
func (*OnIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{14}
}

func (x *OnIssueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnIssueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OnIssueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueStatusRequest) Reset() {
	*x = OnIssueStatusRequest{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueStatusRequest) ProtoMessage() {}

func (x *OnIssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueStatusRequest.ProtoReflect.Descriptor instead.
func (*OnIssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{15}
}

func (x *OnIssueStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OnIssueStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OnIssueStatusRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type OnIssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIssueStatusResponse) Reset() {
	*x = OnIssueStatusResponse{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIssueStatusResponse) ProtoMessage() {}

func (x *OnIssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIssueStatusResponse.ProtoReflect.Descriptor instead.
func (*OnIssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{16}
}

func (x *OnIssueStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnIssueStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Issue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IssueId          string                 `protobuf:"bytes,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId    string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Category         string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory      string                 `protobuf:"bytes,6,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	IssueType        string                 `protobuf:"bytes,7,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	DescriptionShort string                 `protobuf:"bytes,9,opt,name=description_short,json=descriptionShort,proto3" json:"description_short,omitempty"`
	DescriptionLong  string                 `protobuf:"bytes,10,opt,name=description_long,json=descriptionLong,proto3" json:"description_long,omitempty"`
	ImageUrls        []string               `protobuf:"bytes,11,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	BppId            string                 `protobuf:"bytes,12,opt,name=bpp_id,json=bppId,proto3" json:"bpp_id,omitempty"`
	BppUri           string                 `protobuf:"bytes,13,opt,name=bpp_uri,json=bppUri,proto3" json:"bpp_uri,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igm_v1_issue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_api_proto_igm_v1_issue_proto_rawDescGZIP(), []int{17}
}

func (x *Issue) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *Issue) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Issue) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Issue) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Issue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Issue) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *Issue) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *Issue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Issue) GetDescriptionShort() string {
	if x != nil {
		return x.DescriptionShort
	}
	return ""
}

func (x *Issue) GetDescriptionLong() string {
	if x != nil {
		return x.DescriptionLong
	}
	return ""
}

func (x *Issue) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Issue) GetBppId() string {
	if x != nil {
		return x.BppId
	}
	return ""
}

func (x *Issue) GetBppUri() string {
	if x != nil {
		return x.BppUri
	}
	return ""
}

func (x *Issue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Issue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_proto_igm_v1_issue_proto protoreflect.FileDescriptor

const file_api_proto_igm_v1_issue_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/igm/v1/issue.proto\x12\x06igm.v1\"\x83\x03\n" +
	"\x12CreateIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x04 \x01(\tR\vsubCategory\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x05 \x01(\tR\tissueType\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\a \x01(\tR\x0flongDescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12F\n" +
	"\x0fadditional_desc\x18\t \x01(\v2\x1d.igm.v1.AdditionalDescriptionR\x0eadditionalDesc\x12'\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x11.igm.v1.IssueItemR\x05items\"L\n" +
	"\x15AdditionalDescription\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"7\n" +
	"\tIssueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xe9\x01\n" +
	"\x13CreateIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tondc_sent\x18\x06 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\a \x01(\tR\vondcMessage\"\xdd\x01\n" +
	"\x12UpdateIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x04 \x01(\tR\tissueType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12A\n" +
	"\x1dcomplainant_action_short_desc\x18\x06 \x01(\tR\x1acomplainantActionShortDesc\"\xa7\x01\n" +
	"\x13UpdateIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tondc_sent\x18\x04 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\x05 \x01(\tR\vondcMessage\"\xcb\x01\n" +
	"\x11CloseIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x127\n" +
	"\x18complaint_act_short_desc\x18\x06 \x01(\tR\x15complaintActShortDesc\"\xa4\x01\n" +
	"\x12CloseIssueResponse\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tclosed_at\x18\x03 \x01(\tR\bclosedAt\x12\x1b\n" +
	"\tondc_sent\x18\x04 \x01(\bR\bondcSent\x12!\n" +
	"\fondc_message\x18\x05 \x01(\tR\vondcMessage\"E\n" +
	"\x0fGetIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"7\n" +
	"\x10GetIssueResponse\x12#\n" +
	"\x05issue\x18\x01 \x01(\v2\r.igm.v1.IssueR\x05issue\"\\\n" +
	"\x10ListIssueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"M\n" +
	"\x17ListIssueByOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x8e\x01\n" +
	"\x11ListIssueResponse\x12%\n" +
	"\x06issues\x18\x01 \x03(\v2\r.igm.v1.IssueR\x06issues\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1d\n" +
	"\n" +
	"page_sizee\x18\x04 \x01(\x05R\tpageSizee\"p\n" +
	"\x0eOnIssueRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"C\n" +
	"\x0fOnIssueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x14OnIssueStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"I\n" +
	"\x15OnIssueStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd8\x03\n" +
	"\x05Issue\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\tR\aissueId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x06 \x01(\tR\vsubCategory\x12\x1d\n" +
	"\n" +
	"issue_type\x18\a \x01(\tR\tissueType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12+\n" +
	"\x11description_short\x18\t \x01(\tR\x10descriptionShort\x12)\n" +
	"\x10description_long\x18\n" +
	" \x01(\tR\x0fdescriptionLong\x12\x1d\n" +
	"\n" +
	"image_urls\x18\v \x03(\tR\timageUrls\x12\x15\n" +
	"\x06bpp_id\x18\f \x01(\tR\x05bppId\x12\x17\n" +
	"\abpp_uri\x18\r \x01(\tR\x06bppUri\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt2\xcb\x04\n" +
	"\fIssueService\x12F\n" +
	"\vCreateIssue\x12\x1a.igm.v1.CreateIssueRequest\x1a\x1b.igm.v1.CreateIssueResponse\x12F\n" +
	"\vUpdateIssue\x12\x1a.igm.v1.UpdateIssueRequest\x1a\x1b.igm.v1.UpdateIssueResponse\x12C\n" +
	"\n" +
	"CloseIssue\x12\x19.igm.v1.CloseIssueRequest\x1a\x1a.igm.v1.CloseIssueResponse\x12=\n" +
	"\bGetIssue\x12\x17.igm.v1.GetIssueRequest\x1a\x18.igm.v1.GetIssueResponse\x12A\n" +
	"\n" +
	"ListIssues\x12\x18.igm.v1.ListIssueRequest\x1a\x19.igm.v1.ListIssueResponse\x12N\n" +
	"\x10ListIssueByOrder\x12\x1f.igm.v1.ListIssueByOrderRequest\x1a\x19.igm.v1.ListIssueResponse\x12@\n" +
	"\rHandleOnIssue\x12\x16.igm.v1.OnIssueRequest\x1a\x17.igm.v1.OnIssueResponse\x12R\n" +
	"\x13HandleOnIssueStatus\x12\x1c.igm.v1.OnIssueStatusRequest\x1a\x1d.igm.v1.OnIssueStatusResponseB/Z-github/effimove/igm-svc/api/proto/igm/v1;igmbb\x06proto3"

var (
	file_api_proto_igm_v1_issue_proto_rawDescOnce sync.Once
	file_api_proto_igm_v1_issue_proto_rawDescData []byte
)

func file_api_proto_igm_v1_issue_proto_rawDescGZIP() []byte {
	file_api_proto_igm_v1_issue_proto_rawDescOnce.Do(func() {
		file_api_proto_igm_v1_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_igm_v1_issue_proto_rawDesc), len(file_api_proto_igm_v1_issue_proto_rawDesc)))
	})
	return file_api_proto_igm_v1_issue_proto_rawDescData
}

var file_api_proto_igm_v1_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_igm_v1_issue_proto_goTypes = []any{
	(*CreateIssueRequest)(nil),      // 0: igm.v1.CreateIssueRequest
	(*AdditionalDescription)(nil),   // 1: igm.v1.AdditionalDescription
	(*IssueItem)(nil),               // 2: igm.v1.IssueItem
	(*CreateIssueResponse)(nil),     // 3: igm.v1.CreateIssueResponse
	(*UpdateIssueRequest)(nil),      // 4: igm.v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),     // 5: igm.v1.UpdateIssueResponse
	(*CloseIssueRequest)(nil),       // 6: igm.v1.CloseIssueRequest
	(*CloseIssueResponse)(nil),      // 7: igm.v1.CloseIssueResponse
	(*GetIssueRequest)(nil),         // 8: igm.v1.GetIssueRequest
	(*GetIssueResponse)(nil),        // 9: igm.v1.GetIssueResponse
	(*ListIssueRequest)(nil),        // 10: igm.v1.ListIssueRequest
	(*ListIssueByOrderRequest)(nil), // 11: igm.v1.ListIssueByOrderRequest
	(*ListIssueResponse)(nil),       // 12: igm.v1.ListIssueResponse
	(*OnIssueRequest)(nil),          // 13: igm.v1.OnIssueRequest
	(*OnIssueResponse)(nil),         // 14: igm.v1.OnIssueResponse
	(*OnIssueStatusRequest)(nil),    // 15: igm.v1.OnIssueStatusRequest
	(*OnIssueStatusResponse)(nil),   // 16: igm.v1.OnIssueStatusResponse
	(*Issue)(nil),                   // 17: igm.v1.Issue
}
var file_api_proto_igm_v1_issue_proto_depIdxs = []int32{
	1,  // 0: igm.v1.CreateIssueRequest.additional_desc:type_name -> igm.v1.AdditionalDescription
	2,  // 1: igm.v1.CreateIssueRequest.items:type_name -> igm.v1.IssueItem
	17, // 2: igm.v1.GetIssueResponse.issue:type_name -> igm.v1.Issue
	17, // 3: igm.v1.ListIssueResponse.issues:type_name -> igm.v1.Issue
	0,  // 4: igm.v1.IssueService.CreateIssue:input_type -> igm.v1.CreateIssueRequest
	4,  // 5: igm.v1.IssueService.UpdateIssue:input_type -> igm.v1.UpdateIssueRequest
	6,  // 6: igm.v1.IssueService.CloseIssue:input_type -> igm.v1.CloseIssueRequest
	8,  // 7: igm.v1.IssueService.GetIssue:input_type -> igm.v1.GetIssueRequest
	10, // 8: igm.v1.IssueService.ListIssues:input_type -> igm.v1.ListIssueRequest
	11, // 9: igm.v1.IssueService.ListIssueByOrder:input_type -> igm.v1.ListIssueByOrderRequest
	13, // 10: igm.v1.IssueService.HandleOnIssue:input_type -> igm.v1.OnIssueRequest
	15, // 11: igm.v1.IssueService.HandleOnIssueStatus:input_type -> igm.v1.OnIssueStatusRequest
	3,  // 12: igm.v1.IssueService.CreateIssue:output_type -> igm.v1.CreateIssueResponse
	5,  // 13: igm.v1.IssueService.UpdateIssue:output_type -> igm.v1.UpdateIssueResponse
	7,  // 14: igm.v1.IssueService.CloseIssue:output_type -> igm.v1.CloseIssueResponse
	9,  // 15: igm.v1.IssueService.GetIssue:output_type -> igm.v1.GetIssueResponse
	12, // 16: igm.v1.IssueService.ListIssues:output_type -> igm.v1.ListIssueResponse
	12, // 17: igm.v1.IssueService.ListIssueByOrder:output_type -> igm.v1.ListIssueResponse
	14, // 18: igm.v1.IssueService.HandleOnIssue:output_type -> igm.v1.OnIssueResponse
	16, // 19: igm.v1.IssueService.HandleOnIssueStatus:output_type -> igm.v1.OnIssueStatusResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_igm_v1_issue_proto_init() }
func file_api_proto_igm_v1_issue_proto_init() {
	if File_api_proto_igm_v1_issue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_igm_v1_issue_proto_rawDesc), len(file_api_proto_igm_v1_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_igm_v1_issue_proto_goTypes,
		DependencyIndexes: file_api_proto_igm_v1_issue_proto_depIdxs,
		MessageInfos:      file_api_proto_igm_v1_issue_proto_msgTypes,
	}.Build()
	File_api_proto_igm_v1_issue_proto = out.File
	file_api_proto_igm_v1_issue_proto_goTypes = nil
	file_api_proto_igm_v1_issue_proto_depIdxs = nil
}
